apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: fandango-prometheus
spec:
  serviceMonitorSelector:
    matchLabels:
      release: fandango
  resources:
    requests:
      memory: "400Mi"
      cpu: "200m"