apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: fandango-prometheus
spec:
  serviceMonitorSelector:
    matchLabels:
      release: fandango
  resources:
    requests:
      memory: "400Mi"
      cpu: "200m"
  serviceMonitor:
    namespace: default
    selector:
      matchLabels:
        app: fandango-test
  serviceAccountName: fandango-prometheus-sa
  service:
    type: LoadBalancer
  config: 
    log:
      level: info
      format: json
    scrapeInterval: 15s
    evaluationInterval: 15s
    externalLabels:
      monitor: "fandango"
  podMonitorSelector:
    matchLabels:
      app: fandango-test
  nodeSelector:

  